// Auto-generated by crates/tele-codegen. Do not edit manually.
use serde::Serialize;
use serde::de::DeserializeOwned;

/// Typed request marker for advanced API methods.
pub trait AdvancedRequest: Serialize {
    type Response: DeserializeOwned;
    const METHOD: &'static str;
}

#[path = "advanced_business.rs"]
mod advanced_business;
#[path = "advanced_forum.rs"]
mod advanced_forum;
#[path = "advanced_gifts.rs"]
mod advanced_gifts;
#[path = "advanced_misc.rs"]
mod advanced_misc;
#[path = "advanced_payments.rs"]
mod advanced_payments;
#[path = "advanced_stickers.rs"]
mod advanced_stickers;
#[path = "advanced_stories.rs"]
mod advanced_stories;

pub use advanced_business::*;
pub use advanced_forum::*;
pub use advanced_gifts::*;
pub use advanced_misc::*;
pub use advanced_payments::*;
pub use advanced_stickers::*;
pub use advanced_stories::*;
