//! Telegram API service modules.

pub mod advanced;
pub mod bot;
pub mod chats;
pub mod files;
pub mod messages;
pub mod payments;
pub mod stickers;
pub mod updates;

#[cfg(feature = "_async")]
pub use advanced::AdvancedService;
#[cfg(feature = "_blocking")]
pub use advanced::BlockingAdvancedService;
#[cfg(feature = "_blocking")]
pub use bot::BlockingBotService;
#[cfg(feature = "_async")]
pub use bot::BotService;
#[cfg(feature = "_blocking")]
pub use chats::BlockingChatsService;
#[cfg(feature = "_async")]
pub use chats::ChatsService;
#[cfg(feature = "_blocking")]
pub use files::BlockingFilesService;
#[cfg(feature = "_async")]
pub use files::FilesService;
#[cfg(feature = "_blocking")]
pub use messages::BlockingMessagesService;
#[cfg(feature = "_async")]
pub use messages::MessagesService;
#[cfg(feature = "_blocking")]
pub use payments::BlockingPaymentsService;
#[cfg(feature = "_async")]
pub use payments::PaymentsService;
#[cfg(feature = "_blocking")]
pub use stickers::BlockingStickersService;
#[cfg(feature = "_async")]
pub use stickers::StickersService;
#[cfg(feature = "_blocking")]
pub use updates::BlockingUpdatesService;
#[cfg(feature = "_async")]
pub use updates::UpdatesService;
